server:
  port: 8010

spring:
  datasource:
    name: dai_site
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/dai_site
    username: root
    password: Wka2rbJWL0Sk4MQHxPem+KTnjSZUFBoBnN9+wJwHjAaL/IJ/P3DiO48WsbYhm47vz7fxvXykFaENxw+LYFwHdw==
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 50
    maxWait: 60000
    initialSize: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT sysdate FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
